"""
Auto-generated by scripts/download_anvil_schema.py

Do not edit this file directly.

Instead, update the script and run `make anvil_schema`
"""

anvil_schema = {
    'version': 5,
    'tables': [
        {
            'name': 'anvil_activity',
            'columns': [
                {
                    'name': 'activity_id',
                    'datatype': 'string',
                    'array_of': False,
                    'required': True
                },
                {
                    'name': 'activity_type',
                    'datatype': 'string',
                    'array_of': False,
                    'required': False
                },
                {
                    'name': 'used_file_id',
                    'datatype': 'string',
                    'array_of': True,
                    'required': False
                },
                {
                    'name': 'generated_file_id',
                    'datatype': 'string',
                    'array_of': True,
                    'required': False
                },
                {
                    'name': 'used_biosample_id',
                    'datatype': 'string',
                    'array_of': True,
                    'required': False
                },
                {
                    'name': 'source_datarepo_row_ids',
                    'datatype': 'string',
                    'array_of': True,
                    'required': False
                }
            ],
            'primaryKey': [
                'activity_id'
            ],
            'partitionMode': 'none',
            'datePartitionOptions': None,
            'intPartitionOptions': None
        },
        {
            'name': 'anvil_alignmentactivity',
            'columns': [
                {
                    'name': 'alignmentactivity_id',
                    'datatype': 'string',
                    'array_of': False,
                    'required': True
                },
                {
                    'name': 'activity_type',
                    'datatype': 'string',
                    'array_of': False,
                    'required': False
                },
                {
                    'name': 'data_modality',
                    'datatype': 'string',
                    'array_of': True,
                    'required': False
                },
                {
                    'name': 'generated_file_id',
                    'datatype': 'string',
                    'array_of': True,
                    'required': False
                },
                {
                    'name': 'used_file_id',
                    'datatype': 'string',
                    'array_of': True,
                    'required': False
                },
                {
                    'name': 'reference_assembly',
                    'datatype': 'string',
                    'array_of': True,
                    'required': False
                },
                {
                    'name': 'source_datarepo_row_ids',
                    'datatype': 'string',
                    'array_of': True,
                    'required': False
                }
            ],
            'primaryKey': [
                'alignmentactivity_id'
            ],
            'partitionMode': 'none',
            'datePartitionOptions': None,
            'intPartitionOptions': None
        },
        {
            'name': 'anvil_antibody',
            'columns': [
                {
                    'name': 'antibody_id',
                    'datatype': 'string',
                    'array_of': False,
                    'required': True
                },
                {
                    'name': 'target',
                    'datatype': 'string',
                    'array_of': False,
                    'required': False
                },
                {
                    'name': 'source_datarepo_row_ids',
                    'datatype': 'string',
                    'array_of': True,
                    'required': False
                }
            ],
            'primaryKey': [
                'antibody_id'
            ],
            'partitionMode': 'none',
            'datePartitionOptions': None,
            'intPartitionOptions': None
        },
        {
            'name': 'anvil_assayactivity',
            'columns': [
                {
                    'name': 'assayactivity_id',
                    'datatype': 'string',
                    'array_of': False,
                    'required': True
                },
                {
                    'name': 'activity_type',
                    'datatype': 'string',
                    'array_of': False,
                    'required': False
                },
                {
                    'name': 'antibody_id',
                    'datatype': 'string',
                    'array_of': True,
                    'required': False
                },
                {
                    'name': 'assay_type',
                    'datatype': 'string',
                    'array_of': False,
                    'required': False
                },
                {
                    'name': 'data_modality',
                    'datatype': 'string',
                    'array_of': True,
                    'required': False
                },
                {
                    'name': 'generated_file_id',
                    'datatype': 'string',
                    'array_of': True,
                    'required': False
                },
                {
                    'name': 'used_biosample_id',
                    'datatype': 'string',
                    'array_of': True,
                    'required': False
                },
                {
                    'name': 'source_datarepo_row_ids',
                    'datatype': 'string',
                    'array_of': True,
                    'required': False
                }
            ],
            'primaryKey': [
                'assayactivity_id'
            ],
            'partitionMode': 'none',
            'datePartitionOptions': None,
            'intPartitionOptions': None
        },
        {
            'name': 'anvil_biosample',
            'columns': [
                {
                    'name': 'biosample_id',
                    'datatype': 'string',
                    'array_of': False,
                    'required': True
                },
                {
                    'name': 'anatomical_site',
                    'datatype': 'string',
                    'array_of': False,
                    'required': False
                },
                {
                    'name': 'apriori_cell_type',
                    'datatype': 'string',
                    'array_of': True,
                    'required': False
                },
                {
                    'name': 'biosample_type',
                    'datatype': 'string',
                    'array_of': False,
                    'required': False
                },
                {
                    'name': 'disease',
                    'datatype': 'string',
                    'array_of': False,
                    'required': False
                },
                {
                    'name': 'donor_age_at_collection_unit',
                    'datatype': 'string',
                    'array_of': False,
                    'required': False
                },
                {
                    'name': 'donor_age_at_collection_lower_bound',
                    'datatype': 'float',
                    'array_of': False,
                    'required': False
                },
                {
                    'name': 'donor_age_at_collection_upper_bound',
                    'datatype': 'float',
                    'array_of': False,
                    'required': False
                },
                {
                    'name': 'donor_id',
                    'datatype': 'string',
                    'array_of': True,
                    'required': False
                },
                {
                    'name': 'part_of_dataset_id',
                    'datatype': 'string',
                    'array_of': True,
                    'required': False
                },
                {
                    'name': 'source_datarepo_row_ids',
                    'datatype': 'string',
                    'array_of': True,
                    'required': False
                }
            ],
            'primaryKey': [
                'biosample_id'
            ],
            'partitionMode': 'none',
            'datePartitionOptions': None,
            'intPartitionOptions': None
        },
        {
            'name': 'anvil_dataset',
            'columns': [
                {
                    'name': 'dataset_id',
                    'datatype': 'string',
                    'array_of': False,
                    'required': True
                },
                {
                    'name': 'consent_group',
                    'datatype': 'string',
                    'array_of': True,
                    'required': False
                },
                {
                    'name': 'data_use_permission',
                    'datatype': 'string',
                    'array_of': True,
                    'required': False
                },
                {
                    'name': 'owner',
                    'datatype': 'string',
                    'array_of': True,
                    'required': False
                },
                {
                    'name': 'principal_investigator',
                    'datatype': 'string',
                    'array_of': True,
                    'required': False
                },
                {
                    'name': 'registered_identifier',
                    'datatype': 'string',
                    'array_of': True,
                    'required': False
                },
                {
                    'name': 'title',
                    'datatype': 'string',
                    'array_of': False,
                    'required': False
                },
                {
                    'name': 'data_modality',
                    'datatype': 'string',
                    'array_of': True,
                    'required': False
                },
                {
                    'name': 'source_datarepo_row_ids',
                    'datatype': 'string',
                    'array_of': True,
                    'required': False
                }
            ],
            'primaryKey': [
                'dataset_id'
            ],
            'partitionMode': 'none',
            'datePartitionOptions': None,
            'intPartitionOptions': None
        },
        {
            'name': 'anvil_diagnosis',
            'columns': [
                {
                    'name': 'diagnosis_id',
                    'datatype': 'string',
                    'array_of': False,
                    'required': True
                },
                {
                    'name': 'donor_id',
                    'datatype': 'string',
                    'array_of': False,
                    'required': False
                },
                {
                    'name': 'disease',
                    'datatype': 'string',
                    'array_of': True,
                    'required': False
                },
                {
                    'name': 'diagnosis_age_unit',
                    'datatype': 'string',
                    'array_of': False,
                    'required': False
                },
                {
                    'name': 'diagnosis_age_lower_bound',
                    'datatype': 'float',
                    'array_of': False,
                    'required': False
                },
                {
                    'name': 'diagnosis_age_upper_bound',
                    'datatype': 'float',
                    'array_of': False,
                    'required': False
                },
                {
                    'name': 'onset_age_unit',
                    'datatype': 'string',
                    'array_of': False,
                    'required': False
                },
                {
                    'name': 'onset_age_lower_bound',
                    'datatype': 'float',
                    'array_of': False,
                    'required': False
                },
                {
                    'name': 'onset_age_upper_bound',
                    'datatype': 'float',
                    'array_of': False,
                    'required': False
                },
                {
                    'name': 'phenotype',
                    'datatype': 'string',
                    'array_of': True,
                    'required': False
                },
                {
                    'name': 'phenopacket',
                    'datatype': 'string',
                    'array_of': True,
                    'required': False
                },
                {
                    'name': 'source_datarepo_row_ids',
                    'datatype': 'string',
                    'array_of': True,
                    'required': False
                }
            ],
            'primaryKey': [
                'diagnosis_id'
            ],
            'partitionMode': 'none',
            'datePartitionOptions': None,
            'intPartitionOptions': None
        },
        {
            'name': 'anvil_donor',
            'columns': [
                {
                    'name': 'donor_id',
                    'datatype': 'string',
                    'array_of': False,
                    'required': True
                },
                {
                    'name': 'organism_type',
                    'datatype': 'string',
                    'array_of': False,
                    'required': False
                },
                {
                    'name': 'part_of_dataset_id',
                    'datatype': 'string',
                    'array_of': False,
                    'required': False
                },
                {
                    'name': 'phenotypic_sex',
                    'datatype': 'string',
                    'array_of': False,
                    'required': False
                },
                {
                    'name': 'reported_ethnicity',
                    'datatype': 'string',
                    'array_of': True,
                    'required': False
                },
                {
                    'name': 'genetic_ancestry',
                    'datatype': 'string',
                    'array_of': True,
                    'required': False
                },
                {
                    'name': 'source_datarepo_row_ids',
                    'datatype': 'string',
                    'array_of': True,
                    'required': False
                }
            ],
            'primaryKey': [
                'donor_id'
            ],
            'partitionMode': 'none',
            'datePartitionOptions': None,
            'intPartitionOptions': None
        },
        {
            'name': 'anvil_file',
            'columns': [
                {
                    'name': 'file_id',
                    'datatype': 'string',
                    'array_of': False,
                    'required': True
                },
                {
                    'name': 'data_modality',
                    'datatype': 'string',
                    'array_of': True,
                    'required': False
                },
                {
                    'name': 'file_format',
                    'datatype': 'string',
                    'array_of': False,
                    'required': False
                },
                {
                    'name': 'file_size',
                    'datatype': 'integer',
                    'array_of': False,
                    'required': False
                },
                {
                    'name': 'file_md5sum',
                    'datatype': 'string',
                    'array_of': False,
                    'required': False
                },
                {
                    'name': 'reference_assembly',
                    'datatype': 'string',
                    'array_of': True,
                    'required': False
                },
                {
                    'name': 'file_name',
                    'datatype': 'string',
                    'array_of': False,
                    'required': False
                },
                {
                    'name': 'file_ref',
                    'datatype': 'fileref',
                    'array_of': False,
                    'required': False
                },
                {
                    'name': 'is_supplementary',
                    'datatype': 'boolean',
                    'array_of': False,
                    'required': False
                },
                {
                    'name': 'source_datarepo_row_ids',
                    'datatype': 'string',
                    'array_of': True,
                    'required': False
                }
            ],
            'primaryKey': [
                'file_id'
            ],
            'partitionMode': 'none',
            'datePartitionOptions': None,
            'intPartitionOptions': None
        },
        {
            'name': 'anvil_project',
            'columns': [
                {
                    'name': 'project_id',
                    'datatype': 'string',
                    'array_of': False,
                    'required': True
                },
                {
                    'name': 'funded_by',
                    'datatype': 'string',
                    'array_of': True,
                    'required': False
                },
                {
                    'name': 'generated_dataset_id',
                    'datatype': 'string',
                    'array_of': True,
                    'required': False
                },
                {
                    'name': 'principal_investigator',
                    'datatype': 'string',
                    'array_of': True,
                    'required': False
                },
                {
                    'name': 'title',
                    'datatype': 'string',
                    'array_of': False,
                    'required': False
                },
                {
                    'name': 'registered_identifier',
                    'datatype': 'string',
                    'array_of': True,
                    'required': False
                },
                {
                    'name': 'source_datarepo_row_ids',
                    'datatype': 'string',
                    'array_of': True,
                    'required': False
                }
            ],
            'primaryKey': [
                'project_id'
            ],
            'partitionMode': 'none',
            'datePartitionOptions': None,
            'intPartitionOptions': None
        },
        {
            'name': 'anvil_sequencingactivity',
            'columns': [
                {
                    'name': 'sequencingactivity_id',
                    'datatype': 'string',
                    'array_of': False,
                    'required': True
                },
                {
                    'name': 'activity_type',
                    'datatype': 'string',
                    'array_of': False,
                    'required': False
                },
                {
                    'name': 'assay_type',
                    'datatype': 'string',
                    'array_of': True,
                    'required': False
                },
                {
                    'name': 'data_modality',
                    'datatype': 'string',
                    'array_of': True,
                    'required': False
                },
                {
                    'name': 'generated_file_id',
                    'datatype': 'string',
                    'array_of': True,
                    'required': False
                },
                {
                    'name': 'used_biosample_id',
                    'datatype': 'string',
                    'array_of': True,
                    'required': False
                },
                {
                    'name': 'source_datarepo_row_ids',
                    'datatype': 'string',
                    'array_of': True,
                    'required': False
                }
            ],
            'primaryKey': [
                'sequencingactivity_id'
            ],
            'partitionMode': 'none',
            'datePartitionOptions': None,
            'intPartitionOptions': None
        },
        {
            'name': 'anvil_variantcallingactivity',
            'columns': [
                {
                    'name': 'variantcallingactivity_id',
                    'datatype': 'string',
                    'array_of': False,
                    'required': True
                },
                {
                    'name': 'activity_type',
                    'datatype': 'string',
                    'array_of': False,
                    'required': False
                },
                {
                    'name': 'used_file_id',
                    'datatype': 'string',
                    'array_of': True,
                    'required': False
                },
                {
                    'name': 'generated_file_id',
                    'datatype': 'string',
                    'array_of': True,
                    'required': False
                },
                {
                    'name': 'reference_assembly',
                    'datatype': 'string',
                    'array_of': True,
                    'required': False
                },
                {
                    'name': 'data_modality',
                    'datatype': 'string',
                    'array_of': True,
                    'required': False
                },
                {
                    'name': 'source_datarepo_row_ids',
                    'datatype': 'string',
                    'array_of': True,
                    'required': False
                }
            ],
            'primaryKey': [
                'variantcallingactivity_id'
            ],
            'partitionMode': 'none',
            'datePartitionOptions': None,
            'intPartitionOptions': None
        }
    ],
    'relationships': [
        {
            'name': 'from_activity.used_file_id_to_file.file_id',
            'from': {
                'table': 'anvil_activity',
                'column': 'used_file_id'
            },
            'to': {
                'table': 'anvil_file',
                'column': 'file_id'
            }
        },
        {
            'name': 'from_activity.generated_file_id_to_file.file_id',
            'from': {
                'table': 'anvil_activity',
                'column': 'generated_file_id'
            },
            'to': {
                'table': 'anvil_file',
                'column': 'file_id'
            }
        },
        {
            'name': 'from_activity.used_biosample_id_to_biosample.biosample_id',
            'from': {
                'table': 'anvil_activity',
                'column': 'used_biosample_id'
            },
            'to': {
                'table': 'anvil_biosample',
                'column': 'biosample_id'
            }
        },
        {
            'name': 'from_alignmentactivity.used_file_id_to_file.file_id',
            'from': {
                'table': 'anvil_alignmentactivity',
                'column': 'used_file_id'
            },
            'to': {
                'table': 'anvil_file',
                'column': 'file_id'
            }
        },
        {
            'name': 'from_alignmentactivity.generated_file_id_to_file.file_id',
            'from': {
                'table': 'anvil_alignmentactivity',
                'column': 'generated_file_id'
            },
            'to': {
                'table': 'anvil_file',
                'column': 'file_id'
            }
        },
        {
            'name': 'from_assayactivity.antibody_id_to_antibody.antibody_id',
            'from': {
                'table': 'anvil_assayactivity',
                'column': 'antibody_id'
            },
            'to': {
                'table': 'anvil_antibody',
                'column': 'antibody_id'
            }
        },
        {
            'name': 'from_assayactivity.generated_file_id_to_file.file_id',
            'from': {
                'table': 'anvil_assayactivity',
                'column': 'generated_file_id'
            },
            'to': {
                'table': 'anvil_file',
                'column': 'file_id'
            }
        },
        {
            'name': 'from_assayactivity.used_biosample_id_to_biosample.biosample_id',
            'from': {
                'table': 'anvil_assayactivity',
                'column': 'used_biosample_id'
            },
            'to': {
                'table': 'anvil_biosample',
                'column': 'biosample_id'
            }
        },
        {
            'name': 'from_biosample.donor_id_to_donor.donor_id',
            'from': {
                'table': 'anvil_biosample',
                'column': 'donor_id'
            },
            'to': {
                'table': 'anvil_donor',
                'column': 'donor_id'
            }
        },
        {
            'name': 'from_biosample.part_of_dataset_id_to_dataset.dataset_id',
            'from': {
                'table': 'anvil_biosample',
                'column': 'part_of_dataset_id'
            },
            'to': {
                'table': 'anvil_dataset',
                'column': 'dataset_id'
            }
        },
        {
            'name': 'from_donor.part_of_dataset_id_to_dataset.dataset_id',
            'from': {
                'table': 'anvil_donor',
                'column': 'part_of_dataset_id'
            },
            'to': {
                'table': 'anvil_dataset',
                'column': 'dataset_id'
            }
        },
        {
            'name': 'from_diagnosis.donor_id_to_donor.donor_id',
            'from': {
                'table': 'anvil_diagnosis',
                'column': 'donor_id'
            },
            'to': {
                'table': 'anvil_donor',
                'column': 'donor_id'
            }
        },
        {
            'name': 'from_project.generated_dataset_id_to_dataset.dataset_id',
            'from': {
                'table': 'anvil_project',
                'column': 'generated_dataset_id'
            },
            'to': {
                'table': 'anvil_dataset',
                'column': 'dataset_id'
            }
        },
        {
            'name': 'from_sequencingactivity.generated_file_id_to_file.file_id',
            'from': {
                'table': 'anvil_sequencingactivity',
                'column': 'generated_file_id'
            },
            'to': {
                'table': 'anvil_file',
                'column': 'file_id'
            }
        },
        {
            'name': 'from_sequencingactivity.used_biosample_id_to_biosample.biosample_id',
            'from': {
                'table': 'anvil_sequencingactivity',
                'column': 'used_biosample_id'
            },
            'to': {
                'table': 'anvil_biosample',
                'column': 'biosample_id'
            }
        },
        {
            'name': 'from_variantcallingactivity.used_file_id_to_file.file_id',
            'from': {
                'table': 'anvil_variantcallingactivity',
                'column': 'used_file_id'
            },
            'to': {
                'table': 'anvil_file',
                'column': 'file_id'
            }
        },
        {
            'name': 'from_variantcallingactivity.generated_file_id_to_file.file_id',
            'from': {
                'table': 'anvil_variantcallingactivity',
                'column': 'generated_file_id'
            },
            'to': {
                'table': 'anvil_file',
                'column': 'file_id'
            }
        }
    ]
}
