stages:
  - build


# Build Jobs
# Build Job Template
.build_template: &build_template
  image: python:3.6-stretch
  stage: build
  before_script:
    - cat /etc/*-release
    - apt-get update
    - apt-get install unzip
    - mkdir tf-install
    - cd tf-install
    - wget https://releases.hashicorp.com/terraform/0.11.10/terraform_0.11.10_linux_amd64.zip
    - unzip terraform_0.11.10_linux_amd64.zip
    - mv terraform /usr/local/bin/
    - cd ..
    - terraform --version
    - pip install virtualenv

# Develop Build
build_noopdog:
  <<: *build_template
  environment:
    name: noopdog
  script:
    - export AWS_DEFAULT_REGION=us-east-1
    - virtualenv --version
    - virtualenv -p python3 .venv
    - source .venv/bin/activate
    - cd deployments
    - ln -snf noopdog .active
    - cd ..
    - source environment
    - _select noopdog
    - pip install -r requirements.dev.txt
    - cd terraform
    - make gitlab-plan
    - make gitlab-apply
    - cd ..
    - make deploy

  only:
    -  gitlab-dev
