before_script:
  # Copy files like environment.local into the build directory.
  - cp -vR /etc/gitlab/azul/* .

build-image:
  # Build an image containing the build prerequisites (python, terraform, etc). This lets us exploit
  # Docker's layer caching to speed up the build. The image will only be rebuilt after changes to
  # the Dockerfile, requirements.txt or requirements.dev.txt
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY_IMAGE
    - docker build -t $CI_REGISTRY_IMAGE/build .
    - docker push $CI_REGISTRY_IMAGE/build

test:
  # Run the unit tests, deploy and run integration test
  image: $CI_REGISTRY_IMAGE/build
  script:
    - (cd deployments && ln -snf dev .active)
    - source environment
    - source /build/.venv/bin/activate
    - pip list
    - make test
    - make -C terraform auto_apply
    - make deploy
    - make -C terraform auto_apply
    - make integration_test
