variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE
  DOCKER_TAG: $CI_PIPELINE_ID

stages:
  - build_image
  - setup
  - test
  - deploy
  - early_reindex
  - integration_test
  - teardown
  - manual
  - sell_unused_slots

build_image:
  # Build an image containing the build prerequisites (python, terraform, etc).
  # This lets us exploit Docker's layer caching to speed up the build. The
  # image will only be rebuilt after changes to the Dockerfile, 
  # requirements*.txt, common.mk and the Makefile.
  stage: build_image
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY_IMAGE
    - make docker_dev_push .gitlab.env
  artifacts:
    reports:
      dotenv: .gitlab.env

.base:
  image: $BUILD_IMAGE
  before_script:
    - cp -vR /etc/gitlab/azul/* . # Copy files like environment.local into the build directory.
    - source /build/.venv/bin/activate
    - pip list
    - source environment  # load global defaults
    - deployment=$(PYTHONPATH=src python scripts/check_branch.py --print)
    - (cd deployments && ln -snf ${deployment} .active)
    - source environment
    - status_context="gitlab/${azul_gitlab_instance_name}/${AZUL_DEPLOYMENT_STAGE}"
    - make clean
  dependencies:
    - build_image

setup:
  extends: .base
  stage: setup
  script:
    - python scripts/github_status_check.py "${status_context}" pending
  except:
    - schedules

test:
  extends: .base
  stage: test
  script:
    - make format  # Any ill-formatted sources, ...
    - test "$azul_is_sandbox" = 1 && make requirements_update  # ... stale transitive dependencies ...
    - make openapi # ... or changes to the canned OpenAPI definition document ...
    - make check_clean  # would dirty up the working copy and fail the build.
    - make pep8
    - AZUL_DEBUG=0 make test
  except:
    - schedules

deploy:
  extends: .base
  stage: deploy
  script:
    - make auto_deploy
    - make create
  except:
    - schedules
  artifacts:
    paths:
      - terraform/plan.json

integration_test:
  extends: .base
  stage: integration_test
  script:
    - make integration_test
  except:
    - schedules

on_success:
  extends: .base
  stage: teardown
  when: on_success
  script:
    - python scripts/github_status_check.py "${status_context}" success
  except:
    - schedules

on_failure:
  extends: .base
  stage: teardown
  when: on_failure
  script:
    - python scripts/github_status_check.py "${status_context}" failure
  except:
    - schedules

early_reindex:
  extends: .base
  stage: early_reindex
  when: manual
  except:
    - schedules
  script:
    - make reindex
  timeout: 24h

reindex:
  extends: .base
  stage: manual
  when: manual
  except:
    - schedules
  script:
    - make reindex
  timeout: 24h

sell_unused_slots:
  extends: .base
  only:
    - schedules
  script:
    - python3 scripts/sell_unused_slots.py
