variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE
  DOCKER_TAG: $CI_PIPELINE_ID

stages:
  - build_image
  - setup
  - test
  - deploy
  - subscribe
  - early_reindex
  - integration_test
  - teardown
  - manual

build_image:
  # Build an image containing the build prerequisites (python, terraform, etc). This lets us exploit
  # Docker's layer caching to speed up the build. The image will only be rebuilt after changes to
  # the Dockerfile, requirements.txt or requirements.dev.txt
  stage: build_image
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY_IMAGE
    - make docker_dev_push .gitlab.env
  artifacts:
    reports:
      dotenv: .gitlab.env

.base:
  image: $BUILD_IMAGE
  before_script:
    - cp -vR /etc/gitlab/azul/* . # Copy files like environment.local into the build directory.
    - source /build/.venv/bin/activate
    - pip list
    - deployment=$(PYTHONPATH=src python scripts/check_branch.py --print || echo sandbox)
    - (cd deployments && ln -snf ${deployment} .active)
    - source environment
    - make clean
  dependencies:
    - build_image

setup:
  extends: .base
  stage: setup
  script:
    - python scripts/github_status_check.py pending

test:
  extends: .base
  stage: test
  script:
    - make format  # Any ill-formatted sources ...
    - make requirements_update  # ... or stale transitive dependencies ...
    - make check_clean  # would dirty up the working copy and fail the build.
    - make pep8
    - AZUL_DEBUG=0 make test

deploy:
  extends: .base
  stage: deploy
  script:
    - terraform version
    - make package
    - make auto_deploy
    - make create

subscribe:
  extends: .base
  stage: subscribe
  script:
    - make subscribe

integration_test:
  extends: .base
  stage: integration_test
  script:
    - make integration_test

on_success:
  extends: .base
  stage: teardown
  when: on_success
  script:
    - python scripts/github_status_check.py success

on_failure:
  extends: .base
  stage: teardown
  when: on_failure
  script:
    - python scripts/github_status_check.py failure

early_reindex:
  extends: .base
  stage: early_reindex
  when: manual
  script:
    - make reindex
  timeout: 6h 10m  # also see max_timeout in reindex.py

reindex:
  extends: .base
  stage: manual
  when: manual
  script:
    - make reindex
  timeout: 6h 10m  # also see max_timeout in reindex.py
