stages:
  - build_image
  - setup
  - test
  - deploy
  - subscribe
  - early_reindex
  - integration_test
  - teardown
  - manual

build_image:
  # Build an image containing the build prerequisites (python, terraform, etc). This lets us exploit
  # Docker's layer caching to speed up the build. The image will only be rebuilt after changes to
  # the Dockerfile, requirements.txt or requirements.dev.txt
  stage: build_image
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY_IMAGE
    - docker build -t $CI_REGISTRY_IMAGE/build .
    - docker push $CI_REGISTRY_IMAGE/build

.base:
  image: $CI_REGISTRY_IMAGE/build
  before_script:
    - cp -vR /etc/gitlab/azul/* . # Copy files like environment.local into the build directory.
    - source /build/.venv/bin/activate
    - pip list
    - deployment=$(PYTHONPATH=src python scripts/check_branch.py --print || echo sandbox)
    - (cd deployments && ln -snf ${deployment} .active)
    - source environment
    - make clean

setup:
  extends: .base
  stage: setup
  script:
    - python scripts/github_status_check.py pending

test:
  extends: .base
  stage: test
  script:
    - make format
    - make check_clean
    - make pep8
    - AZUL_DEBUG=0 make test

deploy:
  extends: .base
  stage: deploy
  script:
    - make -C terraform plan auto_apply
    - make deploy
    - make -C terraform plan auto_apply

subscribe:
  extends: .base
  stage: subscribe
  script:
    - make subscribe

integration_test:
  extends: .base
  stage: integration_test
  script:
    - make integration_test

on_success:
  extends: .base
  stage: teardown
  when: on_success
  script:
    - python scripts/github_status_check.py success

on_failure:
  extends: .base
  stage: teardown
  when: on_failure
  script:
    - python scripts/github_status_check.py failure

early_reindex:
  extends: .base
  stage: early_reindex
  when: manual
  script:
    - make reindex
  timeout: 1h 10m  # to allow the waiting on message queues by reindex.py time to complete

reindex:
  extends: .base
  stage: manual
  when: manual
  script:
    - make reindex
  timeout: 1h 10m  # to allow the waiting on message queues by reindex.py time to complete
