stages:
  - build


# Build Jobs
# Build Job Template
.build_template: &build_template
  image: python:3.6-stretch
  stage: build
  before_script:
    - cat /etc/*-release
    - pip install virtualenv
    - apt-get update
    - apt-get install unzip
    - mkdir tf-install
    - cd tf-install
    - wget https://releases.hashicorp.com/terraform/0.11.10/terraform_0.11.10_linux_amd64.zip
    - unzip terraform_0.11.10_linux_amd64.zip
    - mv terraform /usr/local/bin/
    - cd ..
    - terraform --version
#  - pip install -r requirements.dev.txt

# Develop Build
build_noopdog:
  <<: *build_template
  environment:
    name: noopdog
  script:
    - virtualenv --version
    - virtualenv -p python3 .venv
    - source .venv/bin/activate
    - cd deployments
    - ln -snf noopdog .active
    - cd ..
    - source environment
    - _select noopdog
#    - pip install -r requirements.dev.txt
#    - make terraform
  #    - make terraform -  need to override commandline switch add new target, force terraform to add the
#    - make deploy
# How to handle tagging tag will cause the job to re-run maybe the committer tags?
# Any tests we can run?
#    - make subscribe
## How to decide make reindex or delete_and_reindex - trigger reindex manually
##one bulild at a time
##kill old reindex
##exclude make delete and reindex till we have kill build II
  only:
    -  gitlab-dev
