[mypy]
warn_unused_configs = True
allow_redefinition = True
explicit_package_bases = True
check_untyped_defs = True
modules =
    azul.types,
    azul.collections,
    azul.args,
    azul.attrs,
    azul.auth,
    azul.azulclient,
    azul.bytes,
    azul.caching,
    azul.chalice,
    azul.bigquery,
    azul.bigquery_reservation,
    azul.csp,
    azul.deployment,
    azul.strings,
    azul.logging,
    azul,
    azul.docker,
    azul.doctests,
    azul.drs,
    azul.dss,
    azul.enums,
    azul.es,
    azul.exceptions,
    azul.files,
    azul.health,
    azul.hmac,
    azul.http,
    azul.iterators,
    azul.json,
    azul.json_freeze,
    azul.lambda_layer,
    azul.lambdas,
    azul.modules,
    azul.oauth2,
    azul.objects,
    azul.queues,
    azul.template,
    azul.terra,
    azul.terraform,
    azul.threads,
    azul.time,
    azul.uuids,
    azul.indexer,
    azul.plugins,
    azul.indexer.document,
    azul.indexer.field,
    azul.indexer.action_controller,
    azul.indexer.mirror_controller,
    azul.service.app_controller,
    azul.indexer.mirror_service,
    azul.digests,
    lambdas.indexer.app,
    azul.schemas,
    azul.indexer.index_controller,
    azul.indexer.index_queue_service,
    azul.indexer.index_repository_service,
    azul.indexer.aggregate,
    test.azul_test_case,
    test.test_tagging,
    scripts.reindex,
    scripts.mirror,
    scripts.post_deploy_tdr,
    scripts.find_in_snapshots,
    scripts.can_bundle

packages =
    azul.openapi

[mypy-furl.*]
follow_untyped_imports = True

[mypy-requests.*]
follow_untyped_imports = True

[mypy-docker.*]
; https://github.com/python/typeshed/issues/13439
follow_untyped_imports = True

[mypy-aws_requests_auth.boto_utils]
follow_untyped_imports = True

