language: python

cache: pip

sudo: required

services:
  - docker

python:
  - 3.6

before_install:
  - (cd deployments && ln -snf dev .active)
  - source environment

install:
  - pip install -r requirements.dev.txt
  - pip install coveralls

script:
  - make test

after_success:
  - coveralls
