language: python

cache: pip

sudo: required

services:
  - docker

python:
  - 3.6

before_install:
  - (cd deployments && ln -snf dev .active)
  - source environment

install:
  - pip install -U setuptools==40.1.0 wheel==0.32.3
  - pip install -r requirements.dev.txt
  - pip install coveralls codecov trufflehog

script:
  - set -e
  # Travis VM images contain a /etc/boto.cfg which ultimately causes moto to
  # look for the Python bindings for GCE. Setting BOTO_CONFIG overrides that.
  - export BOTO_CONFIG=/dev/null
  - make trufflehog
  # Hack: The use of chrgp compensates for a quirk of Docker. The PyCharm image
  # used by make format sets up a user called `developer` and assigns it UID
  # 1000. Travis is running as UID 2000. An alternative would be to pass --user
  # to `docker run` and bind-mount an /etc/passwd that maps that to `developer`.
  # Currently I'm unclear why `make format` works unchanged on Docker
  - sudo chgrp -R 1000 . && make format && sudo chgrp -R $(id -g) .
  - make check_clean
  - make pep8
  - AZUL_DEBUG=0 make test
  - make check_clean

after_success:
  - coveralls
  - codecov
