"""empty message

Revision ID: d7cdac75242a
Revises: be7c97191ac2
Create Date: 2017-03-16 15:03:56.535956

"""

# revision identifiers, used by Alembic.
revision = 'd7cdac75242a'
down_revision = 'be7c97191ac2'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing', sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True))
    op.add_column('billing', sa.Column('deleted_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True))
    op.add_column('billing', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('billing', sa.Column('updated_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True))
    op.create_index(op.f('ix_billing_is_deleted'), 'billing', ['is_deleted'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_billing_is_deleted'), table_name='billing')
    op.drop_column('billing', 'updated_at')
    op.drop_column('billing', 'is_deleted')
    op.drop_column('billing', 'deleted_at')
    op.drop_column('billing', 'created_at')
    ### end Alembic commands ###
