"""empty message

Revision ID: 975a9e3e0e78
Revises: c659370cdf42
Create Date: 2017-02-02 13:36:32.942494

"""

# revision identifiers, used by Alembic.
revision = '975a9e3e0e78'
down_revision = 'c659370cdf42'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing', sa.Column('compute_cost', sa.Numeric(), nullable=True))
    op.add_column('billing', sa.Column('storage_cost', sa.Numeric(), nullable=True))
    op.drop_column('billing', 'cost')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing', sa.Column('cost', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_column('billing', 'storage_cost')
    op.drop_column('billing', 'compute_cost')
    ### end Alembic commands ###
