"""empty message

Revision ID: be7c97191ac2
Revises: 975a9e3e0e78
Create Date: 2017-02-09 13:11:04.508024

"""

# revision identifiers, used by Alembic.
revision = 'be7c97191ac2'
down_revision = '975a9e3e0e78'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing', sa.Column('cost_by_analysis', sa.JSON(), nullable=True))
    op.alter_column('billing', 'compute_cost',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('billing', 'storage_cost',
               existing_type=sa.NUMERIC(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('billing', 'storage_cost',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('billing', 'compute_cost',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.drop_column('billing', 'cost_by_analysis')
    ### end Alembic commands ###
