from abc import (
    ABCMeta,
    abstractmethod,
)
from functools import (
    total_ordering,
)
from itertools import (
    product,
)
import json
import logging
import math
from typing import (
    Any,
    ClassVar,
    Iterable,
    Iterator,
    Self,
    cast,
    final,
)

import attrs

from azul import (
    R,
    config,
)
from azul.attrs import (
    DiscriminatingPolymorphicSerializableAttrs,
    SerializableAttrs,
)
from azul.indexer.field import (
    FieldTypes,
    pass_thru_str,
)
from azul.json import (
    DynamicPolymorphicSerializable,
    Parseable,
)
from azul.types import (
    AnyJSON,
    JSON,
    SupportsLessAndGreaterThan,
    derived_type_params,
)
from azul.uuids import (
    UUIDPartition,
    validate_uuid_prefix,
)

log = logging.getLogger(__name__)

BundleUUID = str
BundleVersion = str


# PyCharm can't handle mixing `attrs` with `total_ordering` and falsely claims
# that comparison operators besides `__lt__` are not defined.
# noinspection PyDataclass
@attrs.frozen(kw_only=True, eq=False)
@total_ordering
class BundleFQID(SerializableAttrs):
    """
    A fully qualified bundle identifier. The attributes defined in this class
    must always be sufficient to decide whether two instances of this class or
    its subclasses identify the same bundle or not. Subclasses may define
    additional attributes to help describe the bundle, but they are forbidden
    from using these attributes in the implementations of their `__eq__` or
    `__hash__` methods, either explicitly or in code generated by `attrs`.
    """
    uuid: BundleUUID
    version: BundleVersion

    def _nucleus(self) -> tuple[str, str]:
        return self.uuid.lower(), self.version.lower()

    @classmethod
    def field_types(cls) -> FieldTypes:
        return {
            'uuid': pass_thru_str,
            'version': pass_thru_str,
        }

    # We can't use attrs' generated implementation because it always
    # considers operands with different types to be unequal, regardless of
    # their inheritance relationships or how their attributes are annotated
    # (e.g. specifying `eq=False` has no effect). We want instances of
    # all subclasses to compare equal as long as `uuid` and `version` are
    # equal. For the same reason, we can't use `typing.Self` in the signature
    # because it would constrain the RHS to instances of subclasses of the LHS.
    @final
    def __eq__(self, other: Any) -> bool:
        """
        >>> b1 = BundleFQID(uuid='a', version='b')
        >>> b2 = BundleFQID(uuid='a', version='b')
        >>> b1 == b2
        True

        >>> p = Prefix.parse('/0')
        >>> s1 = SourceRef(id='x', spec=SimpleSourceSpec.parse('y'), prefix=p)
        >>> sb1 = SourcedBundleFQID(uuid='a', version='b', source=s1)
        >>> sb2 = SourcedBundleFQID(uuid='a', version='b', source=s1)
        >>> sb1 == sb2
        True

        >>> b1 == sb1
        True

        >>> s2 = SourceRef(id='w', spec=SimpleSourceSpec.parse('z'), prefix=p)
        >>> sb3 = SourcedBundleFQID(uuid='a', version='b', source=s2)
        >>> b1 == sb3
        True

        >>> sb1 == sb3
        ... # doctest: +NORMALIZE_WHITESPACE
        Traceback (most recent call last):
        ...
        AssertionError: (('a', 'b'),
        SourceRef(id='x', spec=SimpleSourceSpec(name='y'), prefix=Prefix(common='', partition=0)),
        SourceRef(id='w', spec=SimpleSourceSpec(name='z'), prefix=Prefix(common='', partition=0)))
        """
        if isinstance(other, BundleFQID):
            same_bundle = self._nucleus() == other._nucleus()
            if (
                same_bundle
                and isinstance(self, SourcedBundleFQID)
                and isinstance(other, SourcedBundleFQID)
            ):
                assert self.source == other.source, (self._nucleus(), self.source, other.source)
            return same_bundle
        else:
            return False

    @final
    def __hash__(self) -> int:
        return hash(self._nucleus())

    def __init_subclass__(cls):
        """
        >>> @attrs.frozen(kw_only=True)
        ... class FooBundleFQID(SourcedBundleFQID):
        ...     foo: str
        Traceback (most recent call last):
        ...
        AssertionError: <class 'azul.indexer.FooBundleFQID'>

        >>> @attrs.frozen(kw_only=True, eq=False)
        ... class FooBundleFQID(SourcedBundleFQID):
        ...     foo: str
        """
        super().__init_subclass__()
        assert cls.__eq__ is BundleFQID.__eq__, cls
        assert cls.__hash__ is BundleFQID.__hash__, cls

    # attrs doesn't allow `order=True` when `eq=False`
    def __lt__(self, other: 'BundleFQID') -> bool:
        """
        >>> aa = BundleFQID(uuid='a', version='a')
        >>> ab = BundleFQID(uuid='a', version='b')
        >>> ba = BundleFQID(uuid='b', version='a')
        >>> aa < ab < ba
        True

        >>> ba > ab > aa
        True

        >>> aa <= ab <= ba
        True

        >>> ba >= ab >= aa
        True

        >>> aa != ab != ba
        True
        """
        return self._nucleus() < other._nucleus()


@attrs.frozen(kw_only=True)
class Prefix(Parseable):
    common: str = ''
    partition: int
    of_everything: ClassVar['Prefix']

    digits = '0123456789abcdef'

    def __attrs_post_init__(self):
        validate_uuid_prefix(self.common)
        assert ':' not in self.common, self.common
        assert isinstance(self.partition, int), self.partition
        # Version 4 UUIDs specify fixed bits in the third dash-seperated
        # group. To ensure that any concatenation of common and
        # partition_prefix is a valid UUID prefix, we restrict the number of
        # characters from the concatenation to be within the first
        # dash-seperated group.
        assert len(self.common) + self.partition <= 8, R(
            'Invalid common prefix and partition length', self)

    @classmethod
    def parse(cls, prefix: str) -> Self:
        """
        >>> Prefix.parse('aa/1')
        Prefix(common='aa', partition=1)

        >>> p = Prefix.parse('a')
        Traceback (most recent call last):
        ...
        ValueError: ('Missing partition prefix length', 'a')

        >>> Prefix.parse('aa/')
        Traceback (most recent call last):
        ...
        AssertionError: R('Prefix source cannot end in a delimiter', 'aa/', '/')

        >>> Prefix.parse('8F53/0')
        Traceback (most recent call last):
        ...
        azul.uuids.InvalidUUIDPrefixError: '8F53' is not a valid UUID prefix.

        >>> Prefix.parse('https:foo.edu/0')
        Traceback (most recent call last):
        ...
        azul.uuids.InvalidUUIDPrefixError: 'https:foo.edu' is not a valid UUID prefix.

        >>> Prefix.parse('8f538f53/1').partition_prefixes() # doctest: +NORMALIZE_WHITESPACE
        Traceback (most recent call last):
        ...
        AssertionError: R('Invalid common prefix and partition length',
                          Prefix(common='8f538f53', partition=1))

        >>> list(Prefix.parse('8f538f53/0').partition_prefixes())
        ['8f538f53']

        >>> Prefix.parse('aa/bb')
        Traceback (most recent call last):
        ...
        ValueError: ('Partition prefix length must be an integer', 'bb')

        >>> Prefix.parse('')
        Traceback (most recent call last):
        ...
        AssertionError: R('Cannot parse an empty prefix source')
        """
        source_delimiter = '/'
        assert prefix != '', R('Cannot parse an empty prefix source')
        assert not prefix.endswith(source_delimiter), R(
            'Prefix source cannot end in a delimiter', prefix, source_delimiter)
        partition: str | int
        try:
            entry, partition = prefix.split(source_delimiter)
        except ValueError:
            raise ValueError('Missing partition prefix length', prefix)
        try:
            partition = int(partition)
        except ValueError:
            raise ValueError('Partition prefix length must be an integer', partition)
        validate_uuid_prefix(entry)
        return cls(common=entry, partition=partition)

    @classmethod
    def for_main_deployment(cls, num_elements: int, partition_size: int) -> Self:
        """
        A prefix that divides a source containing the given number of elements
        (subgraphs, files, …) into partitions that rarely exceed the given size.

        >>> n = 8192

        >>> str(Prefix.for_main_deployment(0, n))
        Traceback (most recent call last):
        ...
        ValueError: math domain error

        >>> str(Prefix.for_main_deployment(1, n))
        '/0'

        >>> cases = [-1, 0, 1, 2]

        >>> [str(Prefix.for_main_deployment(n + i, n)) for i in cases]
        ['/0', '/0', '/1', '/1']

        Sources with this many bundles are very rare, so we have a generous
        margin of error surrounding this cutoff point

        >>> m = n * 16
        >>> [str(Prefix.for_main_deployment(m + i, n)) for i in cases]
        ['/1', '/1', '/2', '/2']
        """
        partition = cls._prefix_length(num_elements, partition_size)
        return cls(common='', partition=partition)

    @classmethod
    def for_lesser_deployment(cls, num_elements: int) -> Self:
        """
        A prefix that yields an average of approximately 24 elements per
        source, using an experimentally derived heuristic formula designed to
        minimize manual adjustment of the computed common prefixes. The
        partition prefix length is always 1, even though some partitions may be
        empty, to provide test coverage for handling multiple partitions.

        >>> str(Prefix.for_lesser_deployment(0))
        Traceback (most recent call last):
        ...
        ValueError: math domain error

        >>> str(Prefix.for_lesser_deployment(1))
        '/1'

        >>> cases = [-1, 0, 1, 2]

        >>> n = 64
        >>> [str(Prefix.for_lesser_deployment(n + i)) for i in cases]
        ['/1', '/1', '0/1', '1/1']

        >>> n = 64 * 16
        >>> [str(Prefix.for_lesser_deployment(n + i)) for i in cases]
        ['e/1', 'f/1', '00/1', '10/1']
        """
        digits = f'{num_elements - 1:x}'[::-1]
        length = cls._prefix_length(num_elements, 64)
        assert length < len(digits), num_elements
        return cls(common=digits[:length], partition=1)

    @classmethod
    def _prefix_length(cls, n, m) -> int:
        return max(0, math.ceil(math.log(n / m, len(cls.digits))))

    def partition_prefixes(self) -> Iterator[str]:
        """
        >>> list(Prefix.parse('/0').partition_prefixes())
        ['']

        >>> list(Prefix.parse('a/1').partition_prefixes())
        ['a0', 'a1', 'a2', 'a3', 'a4', 'a5', 'a6', 'a7', 'a8', 'a9', 'aa', 'ab', 'ac', 'ad', 'ae', 'af']

        >>> len(list(Prefix.parse('/2').partition_prefixes()))
        256
        """
        for partition_prefix_digits in product(self.digits, repeat=self.partition):
            complete_prefix = ''.join((self.common, *partition_prefix_digits))
            validate_uuid_prefix(complete_prefix)
            yield complete_prefix

    @property
    def num_partitions(self) -> int:
        """
        Equivalent to `len(self.partition_prefixes())`, but more efficient.

        >>> Prefix.parse('aa/0').num_partitions
        1
        >>> Prefix.parse('/3').num_partitions
        4096
        >>> Prefix.parse('aa/3').num_partitions
        4096
        """
        return len(self.digits) ** self.partition

    def __str__(self):
        """
        >>> s = 'aa/1'
        >>> s == str(Prefix.parse(s))
        True
        """
        return f'{self.common}/{self.partition}'

    def __len__(self):
        """
        >>> len(Prefix.parse('aa/0'))
        2
        >>> len(Prefix.parse('/3'))
        3
        >>> len(Prefix.parse('aa/3'))
        5
        """
        return len(self.common) + self.partition

    def __contains__(self, partition_prefix: str) -> bool:
        """
        Same as `partition_prefix in prefix.partition_prefixes()` but more
        efficient. See also :meth:`partition_prefixes`.

        >>> p0, p1, p2 = Prefix.parse('/0'), Prefix.parse('/1'), Prefix.parse('/2')
        >>> 'a' in p0, 'a' in p1, 'a' in p2
        (False, True, False)

        >>> p1, p2, p3 = Prefix.parse('a/0'), Prefix.parse('a/1'), Prefix.parse('a/2')
        >>> 'ab' in p1, 'ab' in p2, 'ab' in p3
        (False, True, False)

        >>> 'ab' in Prefix.parse('b/1')
        False

        >>> 'ag' in Prefix.parse('a/1')
        False

        >>> 'aB' in Prefix.parse('a/1')
        False
        """
        return (
            partition_prefix.startswith(self.common)
            and len(partition_prefix) == len(self)
            and all(c in self.digits for c in partition_prefix[len(self.common):])
        )


Prefix.of_everything = Prefix.parse('/0')


@attrs.frozen(kw_only=True)
class SourceConfig(SerializableAttrs):
    """
    Configuration on how to index or mirror a specific source.
    """
    mirror: bool


@attrs.frozen(kw_only=True, order=True)
class SourceSpec(Parseable, metaclass=ABCMeta):
    """
    The name of a repository source containing bundles to index. A repository
    has at least one source. Repository plugins whose repository source names
    are structured might want to implement this abstract class. Plugins that
    have simple unstructured names may want to use :class:`SimpleSourceSpec`.
    """
    name: str


@attrs.frozen(kw_only=True)
class SimpleSourceSpec(SourceSpec):
    """
    Default implementation for unstructured source names.
    """

    @classmethod
    def parse(cls, spec: str) -> Self:
        """
        >>> SimpleSourceSpec.parse('https://foo.edu') # doctest: +NORMALIZE_WHITESPACE
        SimpleSourceSpec(name='https://foo.edu')
        """
        self = cls(name=spec)
        assert spec == str(self), spec
        return self

    def __str__(self) -> str:
        """
        >>> s = 'foo:bar/baz'
        >>> s == str(SimpleSourceSpec.parse(s))
        True
        """
        return self.name


@attrs.frozen(kw_only=True, order=True)
class SourceRef[SOURCE_SPEC: SourceSpec](
    DiscriminatingPolymorphicSerializableAttrs,
    DynamicPolymorphicSerializable,
    SupportsLessAndGreaterThan
):
    """
    A reference to a repository source containing bundles to index. A repository
    has at least one source. A source is primarily referenced by its ID but we
    drag the spec along to 1) avoid repeatedly looking it up and 2) ensure that
    the mapping between the two doesn't change while we index a source.

    Note to plugin implementers: Since the source ID can't be assumed to be
    globally unique, plugins should subclass this class, even if the subclass
    body is empty.

    >>> spec = SimpleSourceSpec(name='')
    >>> prefix = Prefix(partition=0)
    >>> sorted([
    ...     SourceRef(id='d', spec=spec, prefix=prefix),
    ...     SourceRef(id='a', spec=spec, prefix=prefix),
    ... ])
    ... # doctest: +NORMALIZE_WHITESPACE
    [SourceRef(id='a', spec=SimpleSourceSpec(name=''), prefix=Prefix(common='', partition=0)),
    SourceRef(id='d', spec=SimpleSourceSpec(name=''), prefix=Prefix(common='', partition=0))]

    """
    id: str = attrs.field(order=str.lower)
    spec: SOURCE_SPEC = attrs.field(order=False)
    prefix: Prefix | None = attrs.field(order=False)

    @classmethod
    def discriminator(cls) -> str:
        return 'type'

    @classmethod
    def spec_cls(cls) -> type[SOURCE_SPEC]:
        spec_cls = derived_type_params(cls, root=SourceRef)[SOURCE_SPEC]
        assert isinstance(spec_cls, type)
        assert issubclass(spec_cls, SourceSpec)
        return cast(type[SOURCE_SPEC], spec_cls)

    def with_prefix(self, prefix: Prefix) -> Self:
        return attrs.evolve(self, prefix=prefix)

    @classmethod
    def field_types(cls) -> FieldTypes:
        return {
            'id': pass_thru_str,
            'spec': pass_thru_str,
            'prefix': pass_thru_str,
            cls.discriminator(): pass_thru_str,
        }


@attrs.frozen(kw_only=True, eq=False)
class SourcedBundleFQID[SOURCE_REF: SourceRef](BundleFQID):
    """
    >>> spec = SimpleSourceSpec(name='')
    >>> prefix = Prefix(partition=0)
    >>> sorted([
    ...     SourcedBundleFQID(uuid='d', version='e', source=SourceRef(id='1', spec=spec, prefix=prefix)),
    ...     SourcedBundleFQID(uuid='a', version='c', source=SourceRef(id='2', spec=spec, prefix=prefix)),
    ...     SourcedBundleFQID(uuid='a', version='b', source=SourceRef(id='3', spec=spec, prefix=prefix)),
    ... ])
    ... # doctest: +NORMALIZE_WHITESPACE
    [SourcedBundleFQID(uuid='a', version='b',
        source=SourceRef(id='3', spec=SimpleSourceSpec(name=''), prefix=Prefix(common='', partition=0))),
    SourcedBundleFQID(uuid='a', version='c',
        source=SourceRef(id='2', spec=SimpleSourceSpec(name=''), prefix=Prefix(common='', partition=0))),
    SourcedBundleFQID(uuid='d', version='e',
        source=SourceRef(id='1', spec=SimpleSourceSpec(name=''), prefix=Prefix(common='', partition=0)))]
    """

    source: SOURCE_REF

    @classmethod
    def source_ref_cls(cls) -> type[SOURCE_REF]:
        ref_cls = derived_type_params(cls, root=SourcedBundleFQID)[SOURCE_REF]
        assert isinstance(ref_cls, type)
        assert issubclass(ref_cls, SourceRef)
        return cast(type[SOURCE_REF], ref_cls)


@attrs.define(kw_only=True)
class Bundle[BUNDLE_FQID: BundleFQID](SerializableAttrs, metaclass=ABCMeta):
    fqid: BUNDLE_FQID

    @property
    def uuid(self) -> BundleUUID:
        return self.fqid.uuid

    @property
    def version(self) -> BundleVersion:
        return self.fqid.version

    @abstractmethod
    def drs_uri(self, manifest_entry: JSON) -> str | None:
        """
        Return the DRS URI to a data file in this bundle, or None if the data
        file is not accessible via DRS.

        :param manifest_entry: the manifest entry of the data file.
        """
        raise NotImplementedError

    def _reject_joiner(self, values: Iterable[AnyJSON]):
        joiner = config.manifest_column_joiner
        # We expect that skipping the check for circular references will provide
        # a small performance benefit. The tradeoff is a risk of infinite
        # recursion, which we consider unlikely enough to be acceptable.
        encoder = json.JSONEncoder(check_circular=False)
        for value in values:
            for chunk in encoder.iterencode(value):
                assert joiner not in chunk, R(
                    f'The string {joiner!r} is disallowed in metadata', self.fqid)

    @abstractmethod
    def reject_joiner(self):
        """
        Raise a requirement error if the manifest joiner occurs in this bundle
        """
        raise NotImplementedError

    @classmethod
    @abstractmethod
    def canning_qualifier(cls) -> str:
        """
        Short string prepended to the file extension to distinguish between
        canned bundle formats originating from different plugins.
        """
        raise NotImplementedError


class BundlePartition(UUIDPartition):
    """
    A binary partitioning of the UUIDs of outer entities in a bundle.

    >>> BundlePartition.root
    BundlePartition(prefix_length=0, prefix=0, group=4)
    """

    #: We use the fifth group because the first group may not produce a random
    #: distribution of the entities in some types of bundles. For example, all
    #: entity UUIDs in an AnVIL replica bundle share a specifc batch prefix.
    #:
    group: int = 4

    #: 512 caused timeouts writing contributions, even in the retry Lambda
    #:
    max_partition_size: ClassVar[int] = 256

    def divisions(self, num_entities: int) -> int:
        return math.ceil(num_entities / self.max_partition_size)
