from abc import (
    ABCMeta,
    abstractmethod,
)
from functools import (
    total_ordering,
)
import json
import logging
import math
from typing import (
    Any,
    ClassVar,
    Iterable,
    cast,
    final,
)

import attrs

from azul import (
    config,
)
from azul.field_type import (
    FieldTypes,
    pass_thru_str,
)
from azul.lib import (
    R,
)
from azul.lib.attrs import (
    SerializableAttrs,
)
from azul.lib.types import (
    AnyJSON,
    JSON,
    derived_type_params,
)
from azul.lib.uuids import (
    UUIDPartition,
)
from azul.source import (
    SourceRef,
)

log = logging.getLogger(__name__)

BundleUUID = str
BundleVersion = str


@attrs.frozen(kw_only=True, eq=False)
@total_ordering
class BundleFQID(SerializableAttrs):
    """
    A fully qualified bundle identifier. The attributes defined in this class
    must always be sufficient to decide whether two instances of this class or
    its subclasses identify the same bundle or not. Subclasses may define
    additional attributes to help describe the bundle, but they are forbidden
    from using these attributes in the implementations of their `__eq__` or
    `__hash__` methods, either explicitly or in code generated by `attrs`.
    """
    uuid: BundleUUID
    version: BundleVersion

    def _nucleus(self) -> tuple[str, str]:
        return self.uuid.lower(), self.version.lower()

    @classmethod
    def field_types(cls) -> FieldTypes:
        return {
            'uuid': pass_thru_str,
            'version': pass_thru_str,
        }

    # We can't use attrs' generated implementation because it always
    # considers operands with different types to be unequal, regardless of
    # their inheritance relationships or how their attributes are annotated
    # (e.g. specifying `eq=False` has no effect). We want instances of
    # all subclasses to compare equal as long as `uuid` and `version` are
    # equal. For the same reason, we can't use `typing.Self` in the signature
    # because it would constrain the RHS to instances of subclasses of the LHS.
    @final
    def __eq__(self, other: Any) -> bool:
        """
        >>> b1 = BundleFQID(uuid='a', version='b')
        >>> b2 = BundleFQID(uuid='a', version='b')
        >>> b1 == b2
        True

        >>> from azul.source import Prefix, SimpleSourceSpec
        >>> p = Prefix.parse('/0')
        >>> s1 = SourceRef(id='x', spec=SimpleSourceSpec.parse('y'), prefix=p)
        >>> sb1 = SourcedBundleFQID(uuid='a', version='b', source=s1)
        >>> sb2 = SourcedBundleFQID(uuid='a', version='b', source=s1)
        >>> sb1 == sb2
        True

        >>> b1 == sb1
        True

        >>> s2 = SourceRef(id='w', spec=SimpleSourceSpec.parse('z'), prefix=p)
        >>> sb3 = SourcedBundleFQID(uuid='a', version='b', source=s2)
        >>> b1 == sb3
        True

        >>> sb1 == sb3
        ... # doctest: +NORMALIZE_WHITESPACE
        Traceback (most recent call last):
        ...
        AssertionError: (('a', 'b'),
        SourceRef(id='x', spec=SimpleSourceSpec(name='y'), prefix=Prefix(common='', partition=0)),
        SourceRef(id='w', spec=SimpleSourceSpec(name='z'), prefix=Prefix(common='', partition=0)))
        """
        if isinstance(other, BundleFQID):
            same_bundle = self._nucleus() == other._nucleus()
            if (
                same_bundle
                and isinstance(self, SourcedBundleFQID)
                and isinstance(other, SourcedBundleFQID)
            ):
                assert self.source == other.source, (self._nucleus(), self.source, other.source)
            return same_bundle
        else:
            return False

    @final
    def __hash__(self) -> int:
        return hash(self._nucleus())

    def __init_subclass__(cls):
        """
        >>> @attrs.frozen(kw_only=True)
        ... class FooBundleFQID(SourcedBundleFQID):
        ...     foo: str
        Traceback (most recent call last):
        ...
        AssertionError: <class 'azul.indexer.FooBundleFQID'>

        >>> @attrs.frozen(kw_only=True, eq=False)
        ... class FooBundleFQID(SourcedBundleFQID):
        ...     foo: str
        """
        super().__init_subclass__()
        assert cls.__eq__ is BundleFQID.__eq__, cls
        assert cls.__hash__ is BundleFQID.__hash__, cls

    # attrs doesn't allow `order=True` when `eq=False`
    def __lt__(self, other: BundleFQID) -> bool:
        """
        >>> aa = BundleFQID(uuid='a', version='a')
        >>> ab = BundleFQID(uuid='a', version='b')
        >>> ba = BundleFQID(uuid='b', version='a')
        >>> aa < ab < ba
        True

        >>> ba > ab > aa
        True

        >>> aa <= ab <= ba
        True

        >>> ba >= ab >= aa
        True

        >>> aa != ab != ba
        True
        """
        return self._nucleus() < other._nucleus()


@attrs.frozen(kw_only=True, eq=False)
class SourcedBundleFQID[SOURCE_REF: SourceRef](BundleFQID):
    """
    >>> from azul.source import Prefix, SimpleSourceSpec
    >>> spec = SimpleSourceSpec(name='')
    >>> prefix = Prefix(partition=0)
    >>> sorted([
    ...     SourcedBundleFQID(uuid='d', version='e', source=SourceRef(id='1', spec=spec, prefix=prefix)),
    ...     SourcedBundleFQID(uuid='a', version='c', source=SourceRef(id='2', spec=spec, prefix=prefix)),
    ...     SourcedBundleFQID(uuid='a', version='b', source=SourceRef(id='3', spec=spec, prefix=prefix)),
    ... ])
    ... # doctest: +NORMALIZE_WHITESPACE
    [SourcedBundleFQID(uuid='a', version='b',
        source=SourceRef(id='3', spec=SimpleSourceSpec(name=''), prefix=Prefix(common='', partition=0))),
    SourcedBundleFQID(uuid='a', version='c',
        source=SourceRef(id='2', spec=SimpleSourceSpec(name=''), prefix=Prefix(common='', partition=0))),
    SourcedBundleFQID(uuid='d', version='e',
        source=SourceRef(id='1', spec=SimpleSourceSpec(name=''), prefix=Prefix(common='', partition=0)))]
    """

    source: SOURCE_REF

    @classmethod
    def source_ref_cls(cls) -> type[SOURCE_REF]:
        ref_cls = derived_type_params(cls, root=SourcedBundleFQID)[SOURCE_REF]
        assert isinstance(ref_cls, type)
        assert issubclass(ref_cls, SourceRef)
        return cast(type[SOURCE_REF], ref_cls)


@attrs.define(kw_only=True)
class Bundle[BUNDLE_FQID: BundleFQID](SerializableAttrs, metaclass=ABCMeta):
    fqid: BUNDLE_FQID

    @property
    def uuid(self) -> BundleUUID:
        return self.fqid.uuid

    @property
    def version(self) -> BundleVersion:
        return self.fqid.version

    @abstractmethod
    def drs_uri(self, manifest_entry: JSON) -> str | None:
        """
        Return the DRS URI to a data file in this bundle, or None if the data
        file is not accessible via DRS.

        :param manifest_entry: the manifest entry of the data file.
        """
        raise NotImplementedError

    def _reject_joiner(self, values: Iterable[AnyJSON]):
        joiner = config.manifest_column_joiner
        # We expect that skipping the check for circular references will provide
        # a small performance benefit. The tradeoff is a risk of infinite
        # recursion, which we consider unlikely enough to be acceptable.
        encoder = json.JSONEncoder(check_circular=False)
        for value in values:
            for chunk in encoder.iterencode(value):
                assert joiner not in chunk, R(
                    f'The string {joiner!r} is disallowed in metadata', self.fqid)

    @abstractmethod
    def reject_joiner(self):
        """
        Raise a requirement error if the manifest joiner occurs in this bundle
        """
        raise NotImplementedError

    @classmethod
    @abstractmethod
    def canning_qualifier(cls) -> str:
        """
        Short string prepended to the file extension to distinguish between
        canned bundle formats originating from different plugins.
        """
        raise NotImplementedError


class BundlePartition(UUIDPartition):
    """
    A binary partitioning of the UUIDs of outer entities in a bundle.

    >>> BundlePartition.root
    BundlePartition(prefix_length=0, prefix=0, group=4)
    """

    #: We use the fifth group because the first group may not produce a random
    #: distribution of the entities in some types of bundles. For example, all
    #: entity UUIDs in an AnVIL replica bundle share a specifc batch prefix.
    #:
    group: int = 4

    #: 512 caused timeouts writing contributions, even in the retry Lambda
    #:
    max_partition_size: ClassVar[int] = 256

    def divisions(self, num_entities: int) -> int:
        return math.ceil(num_entities / self.max_partition_size)
