name: ci

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.2
#    - uses: actions/cache@v2
#      with:
#        path: ~/.cache/pip
#        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
    - name: Test
      run: |
        docker info
        sudo ls /var/lib/docker/image/*
        cat "CHECKING WITHOUT SUDO"
        ls /var/lib/docker/image/*
