name: Velocity report

on:
  schedule:
    # 2230 GMT Tuesday == 1530 PT Tuesday (after demos)
    - cron: '30 22 * * 2'
  workflow_dispatch:
    inputs:
      since:
        description: 'fetch issues after...'
        required: true
        default: YYYY-MM-DD
      until:
        description: 'fetch issues before...'
        required: true
        default: YYYY-MM-DD

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.2
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.2
    - name: Install requirements
      run: pip install -Ur requirements.dev.txt
      # Install requirements directly instead of going through the
      # `source environment` -> virtualenv -> `make requirements` chain because
      # we don't want `source environment` clobbering secrets definition below
    - name: Initialize environment
      run: |
        mkdir wiki/
        echo "::set-env name=PYTHONPATH::$(realpath src)"
        echo "::set-env name=AZUL_DEBUG::0"
    - name: Generate report (cron)
      if: "${{ github.event_name == 'schedule' }}"
      run: |
        export FILENAME=wiki/$(date +'Report for %Y-%m-%d').md
        # Must convert spaces to underscores otherwise wiki upload chokes
        python scripts/velocity.py > "${FILENAME// /_}"
      env:
        azul_velocity_github_user: ${{ secrets.azul_velocity_github_user }}
        azul_velocity_github_token: ${{ secrets.azul_velocity_github_token }}
        azul_velocity_zenhub_key: ${{ secrets.azul_velocity_zenhub_key }}
        azul_velocity_zenhub_pkey: ${{ secrets.azul_velocity_zenhub_pkey }}
        azul_velocity_zenhub_url: ${{ secrets.azul_velocity_zenhub_url }}
    - name: Generate report (manual)
      if: "${{ github.event_name == 'workflow_dispatch' }}"
      run: |
        export FILENAME="wiki/Report for ${{ github.event.inputs.until }}.md"
        # Must convert spaces to underscores otherwise wiki upload chokes
        python scripts/velocity.py --since ${{ github.event.inputs.since }} --until ${{ github.event.inputs.until }} > "${FILENAME// /_}"
      env:
        azul_velocity_github_user: ${{ secrets.azul_velocity_github_user }}
        azul_velocity_github_token: ${{ secrets.azul_velocity_github_token }}
        azul_velocity_zenhub_key: ${{ secrets.azul_velocity_zenhub_key }}
        azul_velocity_zenhub_pkey: ${{ secrets.azul_velocity_zenhub_pkey }}
        azul_velocity_zenhub_url: ${{ secrets.azul_velocity_zenhub_url }}
    - name: Upload Release Notes to Wiki
      uses: docker://decathlon/wiki-page-creator-action:latest
      env:
        ACTION_MAIL: ${{ github.actor }}@users.noreply.github.com
        ACTION_NAME: ${{ github.actor }}
        GH_PAT: ${{ secrets.azul_velocity_github_token }}
        MD_FOLDER: wiki
        OWNER: ${{ github.repository_owner }}
        # Must be specified manually, github.event.repository.name is
        # undefined when github.event == schedule
        REPO_NAME: 'azul'
        TRANSLATE_UNDERSCORE_TO_SPACE: true
        WIKI_PUSH_MESSAGE: "Generated report by ${{ github.event_name }}"