name: Velocity report

on:
  schedule:
    # 2230 GMT Tuesday == 1530 PT Tuesday (after demos)
    - cron: '30 22 * * 2'
  workflow_dispatch:
    inputs:
      since:
        description: 'fetch issues after...'
        required: true
        default: YYYY-MM-DD
      until:
        description: 'fetch issues before...'
        required: true
        default: YYYY-MM-DD

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8.2
    - name: Check out reports repository
      uses: actions/checkout@v2
      with:
        repository: 'ucsc-cgp/boardwalk-velocity-reports'
        token: ${{ secrets.azul_velocity_github_token }}
        path: 'reports/'
    - name: Set up environment
      run: |
        (cd deployments && ln -snf dev .active)
        source environment
        make virtualenv
        source .venv/bin/activate
        make requirements
        cd reports
        git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config --local user.name "${GITHUB_ACTOR}"
    - name: Generate report (cron)
      if: "${{ github.event_name == 'schedule' }}"
      run: |
        FILENAME="Report for $(date +'%Y-%m-%d').md"
        source .venv/bin/activate
        source environment
        python scripts/velocity.py > "reports/${FILENAME}"
        cd reports && git add "${FILENAME}" && git commit -m "${FILENAME}"
      env:
        azul_velocity_github_user: ${{ secrets.azul_velocity_github_user }}
        azul_velocity_github_token: ${{ secrets.azul_velocity_github_token }}
        azul_velocity_zenhub_key: ${{ secrets.azul_velocity_zenhub_key }}
        azul_velocity_zenhub_pkey: ${{ secrets.azul_velocity_zenhub_pkey }}
        azul_velocity_zenhub_url: ${{ secrets.azul_velocity_zenhub_url }}
    - name: Generate report (manual)
      if: "${{ github.event_name == 'workflow_dispatch' }}"
      run: |
        FILENAME="Report for ${{ github.event.inputs.until }}.md"
        source .venv/bin/activate
        source environment
        python scripts/velocity.py \
          --since ${{ github.event.inputs.since }} \
          --until ${{ github.event.inputs.until }} > "reports/${FILENAME}"
        cd reports && git add "${FILENAME}" && git commit -m "${FILENAME}"
      env:
        azul_velocity_github_user: ${{ secrets.azul_velocity_github_user }}
        azul_velocity_github_token: ${{ secrets.azul_velocity_github_token }}
        azul_velocity_zenhub_key: ${{ secrets.azul_velocity_zenhub_key }}
        azul_velocity_zenhub_pkey: ${{ secrets.azul_velocity_zenhub_pkey }}
        azul_velocity_zenhub_url: ${{ secrets.azul_velocity_zenhub_url }}
    - name: Push reports to repo
      uses: ad-m/github-push-action@master
      with:
        repository: 'ucsc-cgp/boardwalk-velocity-reports'
        github_token: ${{ secrets.azul_velocity_github_token }}
        directory: 'reports/'
        branch: 'main'
