version: '2'

services:
  dcc-dashboard-service:
    container_name: "dcc-dashboard-service"
    environment:
      ES_SERVICE: "search-dss-stress-test-index-dev-fjcazd2sn65gtpzduhlyjsh33y.us-east-1.es.amazonaws.com"
      ES_DOMAIN: "search-dss-stress-test-index-dev-fjcazd2sn65gtpzduhlyjsh33y.us-east-1.es.amazonaws.com"
      ES_PORT: "443"
      ES_PROTOCOL: "https"
      ES_FILE_INDEX: "test_data"
    build: .
    ports:
      - "9000:9000"
    networks:
      - esnet
    restart: always
  
networks:
  esnet:
    driver: bridge
